/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List products (cursor paginated) */
        get: {
            parameters: {
                query: {
                    limit: number;
                    /** @description Opaque cursor from a previous page */
                    cursor?: string;
                    /** @description Name contains */
                    q?: string;
                    /** @description Only products with stock > 0 */
                    inStock?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @description ObjectId hex */
                                id: string;
                                sku: string;
                                name: string;
                                /** @description Amount in minor units (paise) */
                                unitPriceMinor: number;
                                currency: string;
                                stock: number;
                                /** Format: date-time */
                                updatedAt: string;
                            }[];
                            nextCursor: string | null;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a product */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ObjectId hex */
                    productId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description ObjectId hex */
                            id: string;
                            sku: string;
                            name: string;
                            /** @description Amount in minor units (paise) */
                            unitPriceMinor: number;
                            currency: string;
                            stock: number;
                            /** Format: date-time */
                            updatedAt: string;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                            };
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/carts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an empty cart */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description ObjectId hex */
                            id: string;
                            status: "OPEN" | "CHECKED_OUT";
                            /** @description ObjectId hex */
                            orderId: string | null;
                            lines: {
                                /** @description ObjectId hex */
                                productId: string;
                                sku: string;
                                name: string;
                                /** @description Amount in minor units (paise) */
                                unitPriceMinor: number;
                                quantity: number;
                                /** @description Amount in minor units (paise) */
                                lineTotalMinor: number;
                                availableStock: number;
                                /** @description False when current stock is below the quantity */
                                isPurchasable: boolean;
                            }[];
                            /** @description Amount in minor units (paise) */
                            subtotalMinor: number;
                            currency: string;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/carts/{cartId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** View a cart with live prices, totals and per-line availability */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ObjectId hex */
                    cartId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description ObjectId hex */
                            id: string;
                            status: "OPEN" | "CHECKED_OUT";
                            /** @description ObjectId hex */
                            orderId: string | null;
                            lines: {
                                /** @description ObjectId hex */
                                productId: string;
                                sku: string;
                                name: string;
                                /** @description Amount in minor units (paise) */
                                unitPriceMinor: number;
                                quantity: number;
                                /** @description Amount in minor units (paise) */
                                lineTotalMinor: number;
                                availableStock: number;
                                /** @description False when current stock is below the quantity */
                                isPurchasable: boolean;
                            }[];
                            /** @description Amount in minor units (paise) */
                            subtotalMinor: number;
                            currency: string;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                            };
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/carts/{cartId}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a product (merges into an existing line) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ObjectId hex */
                    cartId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description ObjectId hex */
                        productId: string;
                        quantity: number;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description ObjectId hex */
                            id: string;
                            status: "OPEN" | "CHECKED_OUT";
                            /** @description ObjectId hex */
                            orderId: string | null;
                            lines: {
                                /** @description ObjectId hex */
                                productId: string;
                                sku: string;
                                name: string;
                                /** @description Amount in minor units (paise) */
                                unitPriceMinor: number;
                                quantity: number;
                                /** @description Amount in minor units (paise) */
                                lineTotalMinor: number;
                                availableStock: number;
                                /** @description False when current stock is below the quantity */
                                isPurchasable: boolean;
                            }[];
                            /** @description Amount in minor units (paise) */
                            subtotalMinor: number;
                            currency: string;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                            };
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                            };
                        };
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                            };
                        };
                    };
                };
                /** @description Default Response */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/carts/{cartId}/items/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a line (404 if the product is not in the cart) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ObjectId hex */
                    cartId: string;
                    /** @description ObjectId hex */
                    productId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description ObjectId hex */
                            id: string;
                            status: "OPEN" | "CHECKED_OUT";
                            /** @description ObjectId hex */
                            orderId: string | null;
                            lines: {
                                /** @description ObjectId hex */
                                productId: string;
                                sku: string;
                                name: string;
                                /** @description Amount in minor units (paise) */
                                unitPriceMinor: number;
                                quantity: number;
                                /** @description Amount in minor units (paise) */
                                lineTotalMinor: number;
                                availableStock: number;
                                /** @description False when current stock is below the quantity */
                                isPurchasable: boolean;
                            }[];
                            /** @description Amount in minor units (paise) */
                            subtotalMinor: number;
                            currency: string;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                            };
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                            };
                        };
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                            };
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Set the absolute quantity of a line */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ObjectId hex */
                    cartId: string;
                    /** @description ObjectId hex */
                    productId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        quantity: number;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description ObjectId hex */
                            id: string;
                            status: "OPEN" | "CHECKED_OUT";
                            /** @description ObjectId hex */
                            orderId: string | null;
                            lines: {
                                /** @description ObjectId hex */
                                productId: string;
                                sku: string;
                                name: string;
                                /** @description Amount in minor units (paise) */
                                unitPriceMinor: number;
                                quantity: number;
                                /** @description Amount in minor units (paise) */
                                lineTotalMinor: number;
                                availableStock: number;
                                /** @description False when current stock is below the quantity */
                                isPurchasable: boolean;
                            }[];
                            /** @description Amount in minor units (paise) */
                            subtotalMinor: number;
                            currency: string;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                            };
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                            };
                        };
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                            };
                        };
                    };
                };
                /** @description Default Response */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                            };
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/carts/{cartId}/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview the totals, optionally with a reward code (read-only)
         * @description Validates the code and returns what checkout would charge now. Nothing is redeemed; placing the order re-checks the code and the prices.
         */
        get: {
            parameters: {
                query?: {
                    couponCode?: string;
                };
                header?: never;
                path: {
                    /** @description ObjectId hex */
                    cartId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Amount in minor units (paise) */
                            subtotalMinor: number;
                            /** @description Amount in minor units (paise) */
                            discountMinor: number;
                            /** @description Amount in minor units (paise) */
                            totalMinor: number;
                            currency: string;
                            coupon: {
                                code: string;
                                percentOff: number;
                            } | null;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                            };
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                            };
                        };
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/carts/{cartId}/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check out a cart (idempotent)
         * @description 201 on first success. A retry with the same Idempotency-Key and body returns 200 with the same order and an `Idempotent-Replayed: true` header.
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Client-generated key (e.g. a UUID). Reuse it when retrying the same checkout. */
                    "idempotency-key": string;
                };
                path: {
                    /** @description ObjectId hex */
                    cartId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        couponCode?: string;
                        /** @description If set and the computed total differs, checkout fails with PRICE_CHANGED */
                        expectedTotalMinor?: number;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description ObjectId hex */
                            id: string;
                            orderNumber: number;
                            /** @description ObjectId hex */
                            cartId: string;
                            /** @enum {string} */
                            status: "PLACED";
                            items: {
                                /** @description ObjectId hex */
                                productId: string;
                                sku: string;
                                name: string;
                                /** @description Amount in minor units (paise) */
                                unitPriceMinor: number;
                                quantity: number;
                                /** @description Amount in minor units (paise) */
                                lineTotalMinor: number;
                            }[];
                            /** @description Amount in minor units (paise) */
                            subtotalMinor: number;
                            /** @description Amount in minor units (paise) */
                            discountMinor: number;
                            /** @description Amount in minor units (paise) */
                            totalMinor: number;
                            currency: string;
                            coupon: {
                                code: string;
                                percentOff: number;
                            } | null;
                            payment: {
                                provider: string;
                                /** @enum {string} */
                                status: "SUCCEEDED";
                            };
                            /** Format: date-time */
                            placedAt: string;
                        };
                    };
                };
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description ObjectId hex */
                            id: string;
                            orderNumber: number;
                            /** @description ObjectId hex */
                            cartId: string;
                            /** @enum {string} */
                            status: "PLACED";
                            items: {
                                /** @description ObjectId hex */
                                productId: string;
                                sku: string;
                                name: string;
                                /** @description Amount in minor units (paise) */
                                unitPriceMinor: number;
                                quantity: number;
                                /** @description Amount in minor units (paise) */
                                lineTotalMinor: number;
                            }[];
                            /** @description Amount in minor units (paise) */
                            subtotalMinor: number;
                            /** @description Amount in minor units (paise) */
                            discountMinor: number;
                            /** @description Amount in minor units (paise) */
                            totalMinor: number;
                            currency: string;
                            coupon: {
                                code: string;
                                percentOff: number;
                            } | null;
                            payment: {
                                provider: string;
                                /** @enum {string} */
                                status: "SUCCEEDED";
                            };
                            /** Format: date-time */
                            placedAt: string;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                            };
                        };
                    };
                };
                /** @description Default Response */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                            };
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                            };
                        };
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                            };
                        };
                    };
                };
                /** @description Default Response */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an order snapshot */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ObjectId hex */
                    orderId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description ObjectId hex */
                            id: string;
                            orderNumber: number;
                            /** @description ObjectId hex */
                            cartId: string;
                            /** @enum {string} */
                            status: "PLACED";
                            items: {
                                /** @description ObjectId hex */
                                productId: string;
                                sku: string;
                                name: string;
                                /** @description Amount in minor units (paise) */
                                unitPriceMinor: number;
                                quantity: number;
                                /** @description Amount in minor units (paise) */
                                lineTotalMinor: number;
                            }[];
                            /** @description Amount in minor units (paise) */
                            subtotalMinor: number;
                            /** @description Amount in minor units (paise) */
                            discountMinor: number;
                            /** @description Amount in minor units (paise) */
                            totalMinor: number;
                            currency: string;
                            coupon: {
                                code: string;
                                percentOff: number;
                            } | null;
                            payment: {
                                provider: string;
                                /** @enum {string} */
                                status: "SUCCEEDED";
                            };
                            /** Format: date-time */
                            placedAt: string;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                            };
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List orders, newest first (admin) */
        get: {
            parameters: {
                query: {
                    limit: number;
                    /** @description Opaque cursor from a previous page */
                    cursor?: string;
                    from?: string;
                    to?: string;
                    couponCode?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @description ObjectId hex */
                                id: string;
                                orderNumber: number;
                                /** @description ObjectId hex */
                                cartId: string;
                                /** @enum {string} */
                                status: "PLACED";
                                items: {
                                    /** @description ObjectId hex */
                                    productId: string;
                                    sku: string;
                                    name: string;
                                    /** @description Amount in minor units (paise) */
                                    unitPriceMinor: number;
                                    quantity: number;
                                    /** @description Amount in minor units (paise) */
                                    lineTotalMinor: number;
                                }[];
                                /** @description Amount in minor units (paise) */
                                subtotalMinor: number;
                                /** @description Amount in minor units (paise) */
                                discountMinor: number;
                                /** @description Amount in minor units (paise) */
                                totalMinor: number;
                                currency: string;
                                coupon: {
                                    code: string;
                                    percentOff: number;
                                } | null;
                                payment: {
                                    provider: string;
                                    /** @enum {string} */
                                    status: "SUCCEEDED";
                                };
                                /** Format: date-time */
                                placedAt: string;
                            }[];
                            nextCursor: string | null;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/coupons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List coupons, newest first (admin) */
        get: {
            parameters: {
                query: {
                    limit: number;
                    /** @description Opaque cursor from a previous page */
                    cursor?: string;
                    status?: "AVAILABLE" | "REDEEMED";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @description ObjectId hex */
                                id: string;
                                code: string;
                                percentOff: number;
                                milestone: number;
                                status: "AVAILABLE" | "REDEEMED";
                                /** @description ObjectId hex */
                                redeemedByOrderId: string | null;
                                /** Format: date-time */
                                generatedAt: string;
                                /** Format: date-time */
                                redeemedAt: string | null;
                            }[];
                            nextCursor: string | null;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /** Generate the coupon for the earliest eligible, unrewarded milestone */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description ObjectId hex */
                            id: string;
                            code: string;
                            percentOff: number;
                            milestone: number;
                            status: "AVAILABLE" | "REDEEMED";
                            /** @description ObjectId hex */
                            redeemedByOrderId: string | null;
                            /** Format: date-time */
                            generatedAt: string;
                            /** Format: date-time */
                            redeemedAt: string | null;
                        };
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rewards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rewards any shopper can use right now, best first */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: string;
                            percentOff: number;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/reports/sales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sales and coupon summary (read-only, consistent snapshot) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            currency: string;
                            totalOrders: number;
                            itemsSold: {
                                /** @description ObjectId hex */
                                productId: string;
                                sku: string;
                                name: string;
                                quantity: number;
                            }[];
                            /** @description Amount in minor units (paise) */
                            grossRevenueMinor: number;
                            /** @description Amount in minor units (paise) */
                            totalDiscountMinor: number;
                            /** @description Amount in minor units (paise) */
                            netRevenueMinor: number;
                            coupons: {
                                generated: number;
                                available: number;
                                redeemed: number;
                            };
                            /** Format: date-time */
                            generatedAt: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
